# helm repo add bitnami https://charts.bitnami.com/bitnami
# helm repo update
# helm install mlflow-minio bitnami/minio \
#   -n mlflow -f values.yaml
#
# Requires secret: mlflow-minio-secret (created by scripts/create-secrets.sh)
#   keys: root-user, root-password

auth:
  existingSecret: mlflow-minio-secret

defaultBuckets: "mlflow-artifacts"

service:
  type: NodePort
  nodePorts:
    api: 30900
    console: 30901

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  size: 20Gi
  storageClass: local-path

# Disable console — bitnami/minio-object-browser image unavailable in some regions
disableWebUI: true
