apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: {{ .Values.certificate.secretName }}
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ .Values.certificate.reflectionNamespaces | quote }}
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  duration: {{ .Values.certificate.duration }}
  renewBefore: {{ .Values.certificate.renewBefore }}
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    {{- range .Values.certificate.dnsNames }}
    - {{ . }}
    {{- end }}
  issuerRef:
    name: {{ .Values.certificate.issuerName }}
    kind: ClusterIssuer
    group: cert-manager.io
