apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: reflector
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: federated-learning
---
apiVersion: v1
kind: Namespace
metadata:
  name: kserve
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-agent
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: v1
kind: Namespace
metadata:
  name: anomaly-poller
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
