apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anomaly-poller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"   # after kafka (wave 1) and kserve
spec:
  project: default
  source:
    repoURL: https://github.com/pritha-athena93/anomaly-detector.git
    targetRevision: main
    path: k8s/manifests/anomaly-poller
  destination:
    server: https://kubernetes.default.svc
    namespace: anomaly-poller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
